// <auto-generated />
using System;
using BL_Crud_Wasm_Net8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BL_Crud_Wasm_Net8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822141712_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BL_Crud_Wasm_Net8.Shared.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Publisher = "P1",
                            ReleaseYear = 2000,
                            Title = "T1"
                        },
                        new
                        {
                            Id = 2,
                            Publisher = "P2",
                            ReleaseYear = 2010,
                            Title = "T2"
                        },
                        new
                        {
                            Id = 3,
                            Publisher = "P3",
                            ReleaseYear = 2020,
                            Title = "T3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
